# Generated by Django 4.2.2 on 2023-10-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disco', '0002_remove_artista_ano_inicio_remove_artista_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disco',
            name='descricao',
            field=models.TextField(max_length=600),
        ),
    ]
